# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

# International Governments
## Beguines Culture and Religion
### How women presided in historical Leuven, Belgium
Beguines were Christian women in the Middle ages who lived in semi-independant communities called Beguinages. These communities were strictly limited to women and those who brought men in were subject to punishments such as praying or fasting. Dissimilar from nuns, they had the opportunity to work (often as a teacher) and manage their own belongings. They still had the freedom to leave the community if they so wished to marry.
|                   | men    | women  | children |
|-------------------|--------|--------|----------|
| population        | 10,000 | 11,000 | 18,000   |
| religious percent | 4%     | 8%     | 7%       |
| percent with jobs | 100%   | 30%    | 0%       |
# types of cuisine
- bread
- vegetable soups
- pottages
- meat: beef, lamb
- drinks: beer
- dessert: pancakes, waffle, fruit

![Beguines portrait](https://bylinetimes.com/wp-content/uploads/2019/05/Schilderij_met_begijnen_door_de_Vlaamse_kunstschilder_Louis_Tytgadt.jpg)

# for more info visit
[Beguines info](https://en.wikipedia.org/wiki/Beguines_and_Beghards)

# final grade calculation for DS3000
## latex format
$$grade = homework_1*.15+homework_2*.15 + lab_1*.1 + lab_2*.1 + lab_3*.1 + quiz_1 * .2 + quiz_2*.2$$

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np

array_a=np.array([[3,8,-2,3],[.5,-1,6,4],[-5,7,-42,2]])
array_b=np.array([[42,38,34],[30,26,22],[18,14,10],[6,2,-2],[-6,-10,-14]])

In [2]:
# uncomment below to print array_a
array_a

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [3]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [4]:
#shape
print(array_a.shape)
print(array_b.shape)
#size
print(array_a.size)
print(array_b.size)
#ndim
print(array_a.ndim)
print(array_b.ndim)
#nbytes
print(array_a.nbytes)
print(array_b.nbytes)

(3, 4)
(5, 3)
12
15
2
2
96
60

In [5]:
t_array_a=array_a.T
t_array_b=array_b.T

In [6]:
#sum_array=array_a+t_array_b
#ValueError: operands could not be broadcast together with shapes (3,4) (3,5)
sum_array=array_a+t_array_b[:,0:4]
sum_array

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

When I first tried to sum array_a and t_array_b, it threw an error saying it wasn't able to broadcast. This was because t_array_b and array_a had a different number of columns before removing the last column from t_array_b.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [7]:
# make sure to import pandas library
import pandas as pd
df_trains=pd.read_csv('train_stations_europe.csv', index_col='id')

In [8]:
df_trains.head()

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
1,Chateau-Arnoux-St-Auban,44.081790,6.001625,NaN,FR,Europe/Paris,True,False,False
2,Chateau-Arnoux-St-Auban,44.061565,5.997373,1.0,FR,Europe/Paris,False,True,False
3,Chateau-Arnoux Mairie,44.063863,6.011248,1.0,FR,Europe/Paris,False,False,False
4,Digne-les-Bains,44.350000,6.350000,NaN,FR,Europe/Paris,True,False,False
6,Digne-les-Bains,44.088710,6.222982,4.0,FR,Europe/Paris,False,True,False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [9]:
belgium=df_trains['country']=='BE'
inCity=df_trains['is_city']==True

belgiumCity=df_trains.loc[belgium & inCity]

print(belgiumCity.head())

                  name   latitude  longitude  parent_station_id country  \
id
5964         Antwerpen  51.221722   4.405860                NaN      BE
5970    Blandain Ville  50.617431   3.263740                NaN      BE
5974         Bruxelles  50.846520   4.351739                NaN      BE
6003       Quevy Ville        NaN        NaN                NaN      BE
6006  Sterpenich Ville        NaN        NaN                NaN      BE

            time_zone  is_city  is_main_station  is_airport
id
5964  Europe/Brussels     True            False       False
5970  Europe/Brussels     True            False       False
5974  Europe/Brussels     True            False       False
6003  Europe/Brussels     True            False       False
6006  Europe/Brussels     True            False       False

In [10]:
belgiumCity.describe()

        latitude  longitude  parent_station_id
count   9.000000   9.000000                0.0
mean   50.719715   4.810847                NaN
std     0.366820   0.996916                NaN
min    49.999779   3.263740                NaN
25%    50.617431   4.351739                NaN
50%    50.718089   4.444643                NaN
75%    50.979756   5.701847                NaN
max    51.221722   6.120155                NaN

The .describe() function ran on series id, latitude, longitude, and parent_station_id. These columns contain numerical data like integers or floats. It did not run on name, country, timezone, or city. These are string columns. The difference is their data type. One is numeric, the other is a string. This means .describe() is used to calculate summary statistics like mean, min, max, etc. for numerical columns.

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope