# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

## **Math mode typing practice:**
$grade = 0.15 \cdot hw_1 + 0.15 \cdot hw_2 + 0.10 \cdot lab_1 + 0.10 \cdot lab_2 + 0.10 \cdot lab_3 + 0.10 \cdot score_{quiz_1} + 0.20 \cdot score_{quiz_2}$

# **Gender Equality Strategy 2026 to 2030**
## **Brief Overview:**
Introduced March 4th, 2026, this strategy is a hope for our future by attacking the gender gaps in multiple spaces across the EU member states.
### **Summary**
This strategy has a heavy focus in fighting online violence by decreasing the production of deepfakes. But beyond that there are other areas of focus as well. Focus areas include:
1) Implementing the Pay Transparency Directive.
2) Having a dedicated policy area for the aim of improving women's healthcare accessibility.
3) Increasing the focus on women, with the ultimate goal of ending the gender gap one policy at a time.
#### **How they will implement this**
|Focus | Why | Relevant Links |
|------|:------------:| --------------:|
|Fighting Cyber Violence | The aim of this is to limit and eliminate sexually explicit deepfakes and deepnudes, which women are often the main subject of. | [Digital Services Act](https://eur-lex.europa.eu/eli/reg/2022/2065/oj/eng) and [Violence Against Women Directive](https://eur-lex.europa.eu/eli/dir/2024/1385)
|Gender and pension pay gap | The aim of this is to improve access to the same opportunities for pay as men have everyday. | [Pay Transparency](https://eur-lex.europa.eu/eli/dir/2023/970/oj)
|Spreading Information | By engaging a larger audience beyond women, to be able to focus on how to counter misinformation and attack the divide between men and women. | N/A

More information about this can be found here: [EU Commission Gender Equality Strategy](https://ec.europa.eu/commission/presscorner/detail/en/ip_26_526)

![EU Commission](https://ec.europa.eu/avservices/avs/files/video6/repository/prod/photo/store//06/91/95/P-069195_00-01_03-MED-173986.jpg)

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [2]:
# make sure to import numpy library
import numpy as np

In [11]:
arraya = np.array([[3,8,-2,3], [.5,-1,6,4],[-5,7,-42,2]])
# arrayb = np.array([[42,38,34], [30,26,22], [18,14,10], [6,2,-2], [-6,-10,-14]])
arrayb = np.array([[42,38,34], [30,26,22], [18,14,10], [6,2,-2]])

In [12]:
# uncomment below to print array_a
arraya

array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [13]:
# uncomment below to print array_b
arrayb

array([[42, 38, 34],
       [30, 26, 22],
       [18, 14, 10],
       [ 6,  2, -2]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [14]:
print("arraya shape:", arraya.shape)
print("arrayb shape:", arrayb.shape)
print("arraya size:", arraya.size)
print("arrayb size:", arrayb.size)
print("arraya dimensions:", arraya.ndim)
print("arrayb dimensions:", arrayb.ndim)
print("arraya nbytes:", arraya.nbytes)
print("arrayb nbytes:", arrayb.nbytes)
t_array_a = arraya.transpose()
t_array_b = arrayb.transpose()
# np.add(t_array_b, arraya)
# the above line throws an error because the sizes of the arrays are not equal.
np.add(t_array_b, arraya)

arraya shape: (3, 4)
arrayb shape: (4, 3)
arraya size: 12
arrayb size: 12
arraya dimensions: 2
arrayb dimensions: 2
arraya nbytes: 96
arrayb nbytes: 96

array([[ 45. ,  38. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

The two arrays as shown above are two different sizes therefore, they were not compatible to be added and led to the error occuring. Therefore after we changed the size of arrayb by removing the last line in the matrix we made the sizes equal and therefore allowed the two arrays to be added.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [15]:
# make sure to import pandas library
import pandas as pd

In [17]:
df = pd.read_csv('train_stations_europe.csv', index_col='id')
df.head()

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
1,Chateau-Arnoux-St-Auban,44.081790,6.001625,NaN,FR,Europe/Paris,True,False,False
2,Chateau-Arnoux-St-Auban,44.061565,5.997373,1.0,FR,Europe/Paris,False,True,False
3,Chateau-Arnoux Mairie,44.063863,6.011248,1.0,FR,Europe/Paris,False,False,False
4,Digne-les-Bains,44.350000,6.350000,NaN,FR,Europe/Paris,True,False,False
6,Digne-les-Bains,44.088710,6.222982,4.0,FR,Europe/Paris,False,True,False

## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [23]:
df = df[(df['country'] == 'BE') & (df['is_city'] == True)]
df.head()

,name,latitude,longitude,parent_station_id,country,time_zone,is_city,is_main_station,is_airport
id,,,,,,,,,
5964,Antwerpen,51.221722,4.405860,NaN,BE,Europe/Brussels,True,False,False
5970,Blandain Ville,50.617431,3.263740,NaN,BE,Europe/Brussels,True,False,False
5974,Bruxelles,50.846520,4.351739,NaN,BE,Europe/Brussels,True,False,False
6003,Quevy Ville,NaN,NaN,NaN,BE,Europe/Brussels,True,False,False
6006,Sterpenich Ville,NaN,NaN,NaN,BE,Europe/Brussels,True,False,False

In [24]:
df.describe()

        latitude  longitude  parent_station_id
count   9.000000   9.000000                0.0
mean   50.719715   4.810847                NaN
std     0.366820   0.996916                NaN
min    49.999779   3.263740                NaN
25%    50.617431   4.351739                NaN
50%    50.718089   4.444643                NaN
75%    50.979756   5.701847                NaN
max    51.221722   6.120155                NaN

#### **What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?**
.describe() ran on latitude, lonitude, and parent_station_id and it didnt run on the non-numerical columns such as bools, string, etc.
The difference from my understanding is that the numerical columns were the ones it ran on, which just essentially means that it is used to summarize the numerical data columns provided.

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope